# Generated by Django 5.1.4 on 2025-01-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypro', '0002_feature_age_feature_bod_feature_city_feature_degree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('op1', models.CharField(max_length=100)),
                ('op2', models.CharField(max_length=100)),
                ('op3', models.CharField(max_length=100)),
                ('op4', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
    ]
