# Generated by Django 5.1.4 on 2025-01-02 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypro', '0004_quizresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizresult',
            old_name='quiz_title',
            new_name='category',
        ),
    ]
