# Generated by Django 5.1.4 on 2025-01-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypro', '0006_remove_question_op1_remove_question_op2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
